---
- id: astyle
  name: astyle
  description: >
    Artistic Style is a source code indenter, formatter, and beautifier for the
    C, C++, C++/CLI, Objective‑C, C# and Java programming languages
  entry: astyle --options=none
  language: python
  types_or:
    - c++
    - c
    - c#
    - cuda
    - java
    - objective-c
