# https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
[project]
name = "pre_commit_placeholder_package"
version = "3.6.10"
description = "See actual project in `packages/*/`"
readme = "packages/astyle/README.md"
# type_a | type_b
requires-python = ">= 3.10"
license = "GPL-3.0-or-later"
keywords = ["formatter"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: MacOS",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX",
  "Operating System :: Unix",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
  "Topic :: Software Development :: Build Tools",
]
dependencies = ["astyle==3.6.17"]

[[project.authors]]
name = "Andre Simon"
email = "as@andre-simon.de"

[[project.authors]]
name = "Jim Pattee"

[[project.authors]]
name = "Tal Davidson"

[project.urls]
"Bug Report" = "https://github.com/Freed-Wu/astyle-wheel/issues"
Download = "https://github.com/Freed-Wu/astyle-wheel/releases"
Homepage = "http://astyle.sourceforge.net"
Source = "https://github.com/Freed-Wu/astyle-wheel"

[build-system]
requires = ["setuptools-generate >= 0.0.6", "setuptools_scm[toml] >= 6.2"]
build-backend = "setuptools.build_meta"

[tool.coverage.report]
exclude_lines = [
  "if TYPE_CHECKING:",
  "if __name__ == .__main__.:",
  "\\s*import tomli as tomllib",
]

[tool.doq]
template_path = "templates"

[tool.mdformat]
number = true

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = [
  # pycodestyle
  "E",
  # pyflakes
  "F",
  # pyupgrade
  "UP",
  # flake8-bugbear
  "B",
  # flake8-simplify
  "SIM",
  # isort
  "I",
]
ignore = ["D205", "D400"]
preview = true

[tool.ruff.format]
docstring-code-format = true
preview = true

[tool.uv.sources.astyle]
workspace = true

[tool.uv.workspace]
members = ["packages/*"]
