---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write

env:
  CMAKE_GENERATOR: Ninja
  files: dist/*
  python-version: 3.x
  cache: pip

jobs:
  build-wheels-and-test:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          # build/_deps/astyle-src/AStyle/src/ASBeautifier.cpp:3914:97:
          # error: expected expression
          # size_t countLS = std::count_if( searchTemplatePattern.begin(),
          # searchTemplatePattern.end(), []( char c ){return c =='<';});
          - macos-latest
          # D:\a\astyle-wheel\astyle-wheel\tests\astyle_test.py:8: in <module>
          #     from astyle.__main__ import main
          # E   ImportError: DLL load failed while importing astyle:
          # The specified module could not be found.
          - windows-latest
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v4
        with:
          path: astyle-wheel
      - uses: actions/setup-python@v5
        with:
          python-version: ${{env.python-version}}
          cache: ${{env.cache}}
      - name: Install dependencies
        run: |
          pip install uv
      - name: Move packages
        if: runner.os != 'windows'
        run: |
          mv astyle-wheel/packages/astyle/* .
          rm -rf astyle-wheel
      - name: Move packages
        if: runner.os == 'windows'
        run: |
          move astyle-wheel/packages/astyle/* .
          Remove-Item -Recurse -Force -Path astyle-wheel
      - uses: docker/setup-qemu-action@v3
        if: runner.os == 'Linux'
      - uses: pypa/cibuildwheel@v2.22
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{matrix.runs-on}}
          path: |
            wheelhouse/*.whl

  build:
    # needs:
    #   - build-wheels-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{env.python-version}}
          cache: ${{env.cache}}
      - name: Install dependencies
        run: |
          pip install uv
      - name: Build sdist
        run: |
          uv build --sdist --package astyle
      - uses: actions/upload-artifact@v4
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          name: artifact-sdist
          path: |
            ${{env.files}}
      - uses: actions/download-artifact@v4
        with:
          pattern: artifact-*
          merge-multiple: true
          path: dist
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # body_path: build/CHANGELOG.md
          files: |
            ${{env.files}}
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          password: ${{secrets.PYPI_API_TOKEN}}
