---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write

env:
  CMAKE_GENERATOR: Ninja
  files: dist/*
  python-version: 3.x
  cache: pip

jobs:
  build-wheels-and-test:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
          # https://github.com/Freed-Wu/astyle-wheel/issues/16
          # - windows-latest
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v4
        with:
          path: astyle-wheel
      - name: Move packages
        if: runner.os != 'windows'
        run: |
          mv astyle-wheel/packages/astyle/* .
          rm -rf astyle-wheel
      - name: Move packages
        if: runner.os == 'windows'
        run: |
          move astyle-wheel/packages/astyle/* .
          Remove-Item -Recurse -Force -Path astyle-wheel
      - uses: actions/setup-python@v5
        with:
          python-version: ${{env.python-version}}
          cache: ${{env.cache}}
      - name: Install dependencies
        run: |
          pip install uv
      - uses: docker/setup-qemu-action@v3
        if: runner.os == 'Linux'
      - uses: pypa/cibuildwheel@v2.23
        env:
          # https://cibuildwheel.pypa.io/en/stable/cpp_standards/#macos-and-deployment-target-versions
          # error: 'path' is unavailable: introduced in macOS 10.15
          MACOSX_DEPLOYMENT_TARGET: "10.15"
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{matrix.runs-on}}
          path: |
            wheelhouse/*.whl

  build:
    needs:
      - build-wheels-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{env.python-version}}
          cache: ${{env.cache}}
      - name: Install dependencies
        run: |
          pip install uv
      - name: Build sdist
        run: |
          uv build --sdist --package astyle
      - uses: actions/upload-artifact@v4
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          name: artifact-sdist
          path: |
            ${{env.files}}
      - uses: actions/download-artifact@v4
        with:
          pattern: artifact-*
          merge-multiple: true
          path: dist
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # body_path: build/CHANGELOG.md
          files: |
            ${{env.files}}
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          password: ${{secrets.PYPI_API_TOKEN}}
