---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write

env:
  files: dist/*
  python-version: 3.x
  cache: pip

jobs:
  build:
    uses: ./.github/workflows/astyle.yml
    secrets: inherit
